# Generated by Django 3.1.1 on 2020-09-29 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('addr', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('apiary_addr', models.CharField(max_length=1000)),
                ('contact_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='time of inspection')),
                ('health', models.IntegerField(default=100)),
                ('honey', models.IntegerField(default=100)),
                ('queen_production', models.IntegerField(default=100)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.hive')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
