# Generated by Django 3.1.1 on 2020-09-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspection',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='bug_catcher_kimbal', max_length=1000),
        ),
    ]
