# Generated by Django 3.1.1 on 2020-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200929_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='equipment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
