# Generated by Django 3.1.1 on 2020-09-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_inspection_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='gain',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='loss',
        ),
        migrations.AddField(
            model_name='inspection',
            name='net_weight_change',
            field=models.FloatField(default=0, verbose_name='change in weight (lbs)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='weight',
            field=models.FloatField(default=100, verbose_name='pounds'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='health',
            field=models.IntegerField(default=10, verbose_name='out of 10'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='honey',
            field=models.IntegerField(default=10, verbose_name='scale from 1-10 (10 hi)'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='queen_production',
            field=models.IntegerField(default=100, verbose_name='bees per month'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('amount_in_inventory', models.IntegerField(default=1)),
                ('condition', models.CharField(max_length=1000)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.inspection')),
            ],
        ),
    ]
