# Generated by Django 3.1.1 on 2020-09-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('addr', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='bug_catcher_kimbal', max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('apiary_addr', models.CharField(max_length=1000)),
                ('contact_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='time of inspection')),
                ('health', models.IntegerField(default=10, verbose_name='out of 10')),
                ('honey', models.IntegerField(default=10, verbose_name='scale from 1-10 (10 hi)')),
                ('queen_production', models.IntegerField(default=100, verbose_name='bees per month')),
                ('weight', models.FloatField(default=100, verbose_name='pounds')),
                ('net_weight_change', models.FloatField(default=0, verbose_name='change in weight (lbs)')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.hive')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('amount_in_inventory', models.IntegerField(default=1)),
                ('condition', models.CharField(max_length=1000)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.inspection')),
            ],
        ),
    ]
