# Generated by Django 3.1.1 on 2020-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to=None),
            preserve_default=False,
        ),
    ]
