# Generated by Django 3.1.1 on 2020-10-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20201002_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
